name: "Deploy pubsub code for CF"

on: 
    push: 
        branches: 
            - main

jobs:
    deploy_my_cf_4_pubsub:
        runs-on: ubuntu-latest
        permissions: 
            contents: 'read'
            id-token: 'write'

        steps:
            - name: checkout my code
              uses: actions/checkout@v3

            - id: 'auth'
              name: 'authenticate manoj google project'
              uses: 'google-github-actions/auth@v1'
              
